version: 1.0.0.{build}
branches:
  only:
  - master
skip_tags: true
configuration: Release
platform: Any CPU
environment:
  SolutionDirectory: .
before_build:
- cmd: >-
    sed -i "s#$(SolutionDir)#.#g" POGOProtos.csproj

    nuget restore -OutputDirectory packages
build:
  verbosity: minimal